### ISSUE TITLE
ステージセレクトシーンの作成

### ISSUE THREAD

**Issue by Harutaka-Tsujino** [human-osaka-game-2018/StarLight_Line#3]
### TODO
- [x] 星座のステージアイコンが回転するように動かす
- [ ] ブラックホールステージのgif画像
- [x] 選択されたステージの詳細データ表示
- [x] ステージへ移動する際の遷移アニメーション

**Comment by taishi-matsumura** [comment]
コミットとissueが紐付けられていてgoodです。
行頭に `#` があると、rebaseする時等にコマンドラインでコミットメッセージを編集するとコメント行として扱われてしまうので `[#3]` とかにした方が良いですよ。
